### PR TITLE
fixes #6, commented names and extended auction table

### LINKED ISSUE #6: Mobile UI table width and sidebar
The app isn't really fit for viewing on a mobile device. This is easily correctable by playing with the css using max-width instead of width to make the width vary with screen size. There are maybe other things that can be changed but I think that will be a priority mostly if we're thinking of adding more information like card formats or something else. The table will still need to be user friendly for people who prefer a classic style. Also, the Screenshot here shows how the navigation menu appears on mobile. It's kind of a mess 
Screenshot_20190413-094239_Ecosia

### PR DESCRIPTION
**Pull request by Sofia-Pika**
width depending on the device

### CODE REVIEW

**Comment by Xoeseko** [comment]
fixes issue #6

**Comment by Sofia-Pika** [comment]
Changing some table names and changing "github trading" to "developers market"

**Review by Xoeseko — APPROVED** [review]
The file contributions.component.html slid into a merge commit which is not very transparent but works.

**Comment by Xoeseko** [comment]
@all-contributors please add @Sofia-Pika for design and testing her committment to the early stages of this project will ever be appreciated !

**Pull request merged**
